spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/sastbackendwoc?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080
